CREATE TABLE videos(
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    overview VARCHAR(5000) NOT NULL,
    unique_id VARCHAR(256) NOT NULL UNIQUE,
    channel_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE (title, channel_id),
    FOREIGN KEY (channel_id) REFERENCES channels(id)
)