CREATE TABLE videos(
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    overview VARCHAR(5000) NOT NULL,
    views INT UNSIGNED NOT NULL,
    duration FLOAT(6, 4) UNSIGNED NOT NULL,
    video_path VARCHAR(256) NOT NULL UNIQUE,
    thumbnail_path VARCHAR(256) NOT NULL UNIQUE,
    unique_id VARCHAR(256) NOT NULL UNIQUE,
    channel_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (channel_id) REFERENCES channels(id)
)